package com.venus_customer.util

enum class TripStatus(val type: Int){
    REQUESTED(0),
    ACCEPTED(1),
    STARTED(2),
    ENDED(3),
    REJECTED_BY_DRIVER(4),
    CANCELLED_BY_CUSTOMER(5),
    TIMEOUT(6),
    ACCEPTED_BY_OTHER_DRIVER(7),
    ACCEPTED_THEN_REJECTED(8),
    CANCELLED_ACCEPTED_REQUEST(10),
    RIDE_CANCELLED_BY_CUSTOMER(13),
    ARRIVED(14),
}